--calling table drops
@remove.sql

--adding objects
@project_type.sql

--Creating tables
--Term
create table terms (term_id number PRIMARY KEY, 
                    term_name char(6) NOT NULL);

--Domain
create table domains (domain_id number PRIMARY KEY, 
                        domain varchar2(50) NOT NULL, 
                        domain_description varchar2(500) NOT NULL);

--Course
create table courses (course_id varchar2(10) PRIMARY KEY, 
                    course_title varchar2(50) NOT NULL,
                    theory_hours number NOT NULL, 
                    lab_hours number NOT NULL, 
                    work_hours number NOT NULL,
                    description varchar2(1000) NOT NULL, 
                    domain_id REFERENCES domains(domain_id), 
                    term_id REFERENCES terms(term_id));

--Competency
create table competencies (competency_id char(4) PRIMARY KEY, 
                            competency varchar2(250) NOT NULL,
                            competency_achievement varchar2(500) NOT NULL ,
                            competency_type varchar2(10) NOT NULL);
                        
--Element
create table elements (element_id number generated always as identity PRIMARY KEY, 
                        element_order number NOT NULL, 
                        element varchar2(250) NOT NULL,
                        element_criteria varchar2(500) NOT NULL, 
                        competency_id REFERENCES competencies(competency_id));
                    
--Courses_Elements (Bridging)
create table courses_elements (course_id REFERENCES courses(course_id) ON DELETE CASCADE, 
                                element_id REFERENCES elements(element_id) ON DELETE CASCADE, 
                                element_hours number NOT NULL);

--App_Users
create table app_users (id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            email VARCHAR2(100) NOT NULL,
                            password VARCHAR2(102) NOT NULL,
                            name VARCHAR2(1000) NOT NULL,
                            avatar_path VARCHAR2(2000),
                            account_type VARCHAR2(20) CHECK (account_type IN ('MEMBER', 'ADMIN_USER_GP', 'ADMINISTRATOR_GP')),
                            is_locked number CHECK (is_locked IN (1, 0)));


--adding logging mechanisms
@logging.sql

--calling creation of sample data
@inserting.sql

--adding views
@views.sql

--adding package
@courses_package.sql
Commit;

